name: Renovate

on:
  push

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v40.1.12
      with:
        token: ${{ secrets.ROBONEXT_PAT }}
        configurationFile: renovate.json
      env:
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        LOG_LEVEL: debug
        RENOVATE_ONBOARDING: false
